
name: run the sr_insects static_flow test.

on:
  pull_request:
    types: [opened, edited, reopened]
  push:
    branches:
      - v03_wip

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip3 install .
        travis/flow_autoconfig.sh
        travis/ssh_localhost.sh
         
    - name: Setup Static test.
      run: |
        cd ${HOME}; pwd; ls ; 
        echo hoho
        cd ${HOME}/sr_insects/static_flow; ./flow_setup.sh

    # Enable tmate debugging of manually-triggered workflows if the input option was provided
    # https://github.com/marketplace/actions/debugging-with-tmate
    # 
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    #  #if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

    - name: Limit Static test.
      run: |
        cd ${HOME}/sr_insects/static_flow; ./flow_limit.sh

    - name: Check Static test.
      run: |
        cd ${HOME}/sr_insects/static_flow; ./flow_check.sh
